<?php

return array (
  'version' => '5.7.2',
  'title' => 'Resources',
  'type' => 'resource',
  'id' => '61ec9e489bd4c',
  'updated' => 1655958658,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '20',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '62b3ec273cac08' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Topics',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'resource_topics',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62b3ec273cac08',
    ),
    '62b3ec3fd89374' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Types',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'resource_types',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62b3ec3fd89374',
    ),
    '62b3ec7b651eb8' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'F j, Y g:i a',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '62b3ec7b651eb8',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'resize_columns' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);