<?php

return array (
  'version' => '5.7.4',
  'title' => 'Events',
  'type' => 'event',
  'id' => '62b3de1abd13c',
  'updated' => 1667523787,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '20',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '62b3deb870624c' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '',
      'width_unit' => '%',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '50',
      'image_size_h' => '50',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62b3deb870624c',
    ),
    '62b3e5c601cac0' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Type',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'event_types',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '',
      'name' => '62b3e5c601cac0',
    ),
    '6364649c449ba4' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Focus Areas',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'focus_areas',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6364649c449ba4',
    ),
    '62b3de64a353f8' => 
    array (
      'type' => 'column-meta',
      'label' => 'Start Date',
      'width' => '',
      'width_unit' => '%',
      'field' => 'event_start_date',
      'field_type' => 'date',
      'date_format' => 'wp_default',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62b3de64a353f8',
    ),
    '62b3e4cb116874' => 
    array (
      'type' => 'field_62b3be6133f18',
      'label' => 'Start Time',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'acf',
      'export' => 'off',
      'sort' => 'on',
      'search' => 'on',
      'name' => '62b3e4cb116874',
    ),
    '62b3e4ee999998' => 
    array (
      'type' => 'field_62b3bf259b01e',
      'label' => 'End Time',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'acf',
      'export' => 'off',
      'sort' => 'on',
      'search' => 'on',
      'name' => '62b3e4ee999998',
    ),
    '62b3e45ecb8520' => 
    array (
      'type' => 'field_62b3c444cff7e',
      'label' => 'RSVP?',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62b3e45ecb8520',
    ),
    '62b3e4796bc6a8' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'F j, Y g:i a',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '62b3e4796bc6a8',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'resize_columns' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);