<?php

return array (
  'version' => '5.7.2',
  'title' => 'Team Member',
  'type' => 'team',
  'id' => '62b3ecbc08d7d',
  'updated' => 1655964378,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '20',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '62b3ecae1645a0' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '',
      'width_unit' => '%',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '50',
      'image_size_h' => '50',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62b3ecae1645a0',
    ),
    '62b3edbd5f7cec' => 
    array (
      'type' => 'column-meta',
      'label' => 'First',
      'width' => '',
      'width_unit' => '%',
      'field' => 'team_first_name',
      'field_type' => 'excerpt',
      'string_limit' => 'word_limit',
      'excerpt_length' => '20',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62b3edbd5f7cec',
    ),
    '62b3ede194fdf4' => 
    array (
      'type' => 'column-meta',
      'label' => 'Last',
      'width' => '',
      'width_unit' => '%',
      'field' => 'team_last_name',
      'field_type' => 'excerpt',
      'string_limit' => 'word_limit',
      'excerpt_length' => '20',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62b3ede194fdf4',
    ),
    '62b3ed8f0dd2f0' => 
    array (
      'type' => 'column-meta',
      'label' => 'Position',
      'width' => '',
      'width_unit' => '%',
      'field' => 'team_position',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'off',
      'editable_type' => 'text',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62b3ed8f0dd2f0',
    ),
    '62b3ecd8ac8b44' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Roles',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'team_roles',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '',
      'name' => '62b3ecd8ac8b44',
    ),
    '62b3ecca041894' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'F j, Y g:i a',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '62b3ecca041894',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'resize_columns' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);