<?php

return array (
  'version' => '5.7.4',
  'title' => 'Pages',
  'type' => 'page',
  'id' => '62b3ed2fb6171',
  'updated' => 1668130154,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '636da563e6e978' => 
    array (
      'type' => 'field_5ba74defea3b7',
      'label' => 'Blocks',
      'width' => '',
      'width_unit' => '%',
      'flex_display' => 'count',
      'export' => 'off',
      'search' => 'on',
      'name' => '636da563e6e978',
    ),
    'author' => 
    array (
      'type' => 'author',
      'label' => 'Author',
      'width' => '10',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'author',
    ),
    '62b3ed280a7ef8' => 
    array (
      'type' => 'column-modified',
      'label' => 'Last Modified',
      'width' => '',
      'width_unit' => '%',
      'date_format' => 'F j, Y g:i a',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '62b3ed280a7ef8',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'resize_columns' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);